export const UPDATE_CLICKED = 'UPDATE_CLICKED'
export const RESET_CLICKS = 'RESET_CLICKS'

export const UPDATE_BASE_OR_SAUCE = 'UPDATE_BASE_OR_SAUCE'
export const RESET_BASE_CLICKS = 'RESET_BASE_CLICKS'
export const RESET_SAUCE_CLICKS = 'RESET_SAUCE_CLICKS'

export const CALCULATE_TOTAL = 'CALCULATE_TOTAL' 

export const UPDATE_CHECKBOXES = 'UPDATE_CHECKBOXES'
export const RESET_CHECKBOXES = 'RESET_CHECKBOXES'